-- Add up migration script here
CREATE TABLE IF NOT EXISTS urls (
    id CHAR(36) PRIMARY KEY NOT NULL,
    code VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
